name: V55C RX Build

on:
  workflow_call:

jobs:
  build-vars:
    runs-on: ubuntu-latest
    outputs:
      build-type: ${{ steps.detect.outputs.build-type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Detect build type
        id: detect
        run: |
          if [ -f "pom.xml" ]; then
            echo "build-type=maven" >> $GITHUB_OUTPUT
          elif [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            echo "build-type=gradle" >> $GITHUB_OUTPUT
          elif [ -f "package.json" ]; then
            echo "build-type=npm" >> $GITHUB_OUTPUT
          elif [ -f "*.csproj" ] || [ -f "*.sln" ]; then
            echo "build-type=dotnet" >> $GITHUB_OUTPUT
          else
            echo "build-type=generic" >> $GITHUB_OUTPUT
          fi

  build:
    needs: build-vars
    uses: ./.github/workflows/am-build.yml
    secrets: inherit